generatorName: go

gitHost: github.com
gitUserId: tagur87
gitRepoId: go-netbox

packageName: netbox
isGoSubmodule: true
withGoMod: false

globalProperty:
  apiDocs: false
  modelDocs: false
  apiTests: false
  modelTests: false

additionalProperties:
  disallowAdditionalPropertiesIfNotPresent: "false"
  packageVersion: "1"
